### ISSUE TITLE
document Undocumented plantuml features

### ISSUE THREAD

**Issue by VladimirAlexiev** [plantuml/plantuml#261]
There are many plantuml undocumented features and settings captured in the [forum (Q&A)](http://forum.plantuml.net)
Many of them also don't appear with `java -jar plantuml.jar -language`.

The list comes mostly from [#7095](http://forum.plantuml.net/7095), [#7140](http://forum.plantuml.net/7140) thanks to @Anthony-Gaudino,
and was complemented, categorized, and converted to a task list by @VladimirAlexiev.

NOTE: [Ashley's PlantUML Doc](https://plantuml-documentation.readthedocs.io/) by Ashley Engelund is a good example how the total documentation can be structured.
It's created with reStructuredText (rST) and sphinx.
In particular [This Site](https://plantuml-documentation.readthedocs.io/en/latest/this_site/index.html) describes some advanced doc generation: "`javasphinx`: I’ve written some Java code to extract information directly from PlantUML code. The extracted info is then used as input to my sphinx files. I also have some python code that creates some of the .puml files and initial rST code."

## Preprocessor, Includes, Sectioning
[preprocessing-v2](http://plantuml.com/preprocessing-v2)
- [ ] [#6577](http://forum.plantuml.net/6577) Ability to include blocks ("subsections") of code 
- [ ] [#7838](http://forum.plantuml.net/7838) `!pragma http.proxyHost`
- [ ] [#6289](http://forum.plantuml.net/6289) `%filename%` and `%filenameNoExtension%`
- [ ] [#6199](http://forum.plantuml.net/6199) `%PLANTUML_VERSION%`
- [ ] [#5968](http://forum.plantuml.net/5968) `%filedate%`
- [ ] [#5769](http://forum.plantuml.net/5769) `%filename%` and `%dirpath%` variables
- [ ] [#5171](http://forum.plantuml.net/5171) Boolean not `!` and parenthesis on `!ifdef`
- [ ] [#3868](http://forum.plantuml.net/3868) Use tilde `~` to escape `@startuml`
- [ ] [#5483](http://forum.plantuml.net/5483) `@startuml` filename for automatic extensions
- [ ] [#4467](http://forum.plantuml.net/4467) `@startuml` with identifier for includes
- [ ] [#1466](http://forum.plantuml.net/1466) `@startuml{OPTIONS}`
- [ ] [#4596](http://forum.plantuml.net/4596) `\startXXX`  instead  of `@startXXX`
- [ ] [#5769](http://forum.plantuml.net/5769) `@startdef` and `@enddef`
- [ ] [#1525](http://forum.plantuml.net/1525), [#5793](http://forum.plantuml.net/5793) `@pause @unpause`
- [ ] [#1525](http://forum.plantuml.net/1525) `@pause @unpause @continue @append`
- [ ] [#4266](http://forum.plantuml.net/4266) `-config` parameter
- [ ] [#2410](http://forum.plantuml.net/2410) Multiple include paths
- [ ] [#7337](http://forum.plantuml.net/7337) Tags to include individual pieces
- [ ] [#7337](http://forum.plantuml.net/7337) `remove / restore`

## Running and Output
[command-line](http://plantuml.com/command-line)
- [ ] [#4752](http://forum.plantuml.net/4752) Output Braille diagrams (-tbraille)
- [x] [#5037](http://forum.plantuml.net/5037) `-pipemap` parameter (HTML clickable maps): [command-line#standard_input_output](http://wiki.plantuml.net/site/command-line#standard_input_output)
- [x] [#3562](http://forum.plantuml.net/3562) diagram code is embedded in PNG metadata (`-metadata -checkmeta`)
- [ ] [#1601](http://forum.plantuml.net/1601) `-gui` parameter accepts a path
- [ ] [#3214](http://forum.plantuml.net/3214) `-eps:text` parameter

AsciiArt output with `-ttxt` or `-tutxt`
- [ ] [#4147](http://forum.plantuml.net/4147) skinparam maxAsciiMessageLength 

[latex](http://plantuml.com/latex) output with `-tlatex` through Tikz
- [ ] [#1798](http://forum.plantuml.net/1798) latex-tikz-support anything more to document?
- [ ] Latex "see result online" (eg https://www.writelatex.com/read/pgkkspzgzgpb) doesn't work because need to migrate to overleaf
- [ ] [#6495](http://forum.plantuml.net/6495) skinparam tikzFont
- [ ] [#3558](http://forum.plantuml.net/3558) Latex link `[[latex://]]`

SVG output with `tsvg`:
- [ ] [#5453](http://forum.plantuml.net/5453) skinparam pathHoverColor
- [ ] [#7334](http://forum.plantuml.net/7334) skinparam svgDimensionStyle

## Layout
- [ ] [#4418](http://forum.plantuml.net/4418), [#3111](http://forum.plantuml.net/3111), [#4045](http://forum.plantuml.net/4045) `!pragma svek_trace`
- [ ] [#1343](http://forum.plantuml.net/1343) `!pragma aspect`
- [ ] [#1226](http://forum.plantuml.net/1226) `!pragma ratio`
- [ ] [#977](http://forum.plantuml.net/977) `skinparam nodesep`
- [ ] [#977](http://forum.plantuml.net/977) `skinparam ranksep`
- [ ] [#4247](http://forum.plantuml.net/4247) `hide unlinked`
- [ ] [#3188](http://forum.plantuml.net/3188) `norank` arrow option
- [ ] [#8365](http://forum.plantuml.net/8365) `hidden` and `norank`
- [ ] [#4418](http://forum.plantuml.net/4418), [#1132](http://forum.plantuml.net/1132), [#3231](http://forum.plantuml.net/3231), [#3111](http://forum.plantuml.net/3111), [#3143](http://forum.plantuml.net/3143) `!pragma horizontalLineBetweenDifferentPackageAllowed`
- [ ] [#1296](http://forum.plantuml.net/1296) `skinparam minClassWidth` and `skinparam sameClassWidth`
- [ ] [#4637](http://forum.plantuml.net/4637) skinparam minClassWidth on sequence diagram
- [ ] [#2538](http://forum.plantuml.net/2538) `layout_new_line` for disconnected parts
- [ ] [#3118](http://forum.plantuml.net/3118) `skinparam padding`
- [ ] [#5493](http://forum.plantuml.net/5493) `skinparam ParticipantPadding` and `skinparam BoxPadding`

## Text and Links
[Creole](http://plantuml.com/creole), [Link](http://plantuml.com/link), [ASCII Math, JLatexMath](http://plantuml.com/ascii-math)
- [ ] [#3104](http://forum.plantuml.net/3104) Use `\` for multiline stuff
- [ ] [#3055](http://forum.plantuml.net/3055) Align text with `\l` and `\r`
- [ ] [#3601](http://forum.plantuml.net/3601) Creole on class titles with `as`
- [ ] [issues/104](https://github.com/plantuml/plantuml/issues/104) skinparam wrapWidth and skinparam wrapMessageWidth
- [ ] [#3820](http://forum.plantuml.net/3820) skinparam tabSize
- [ ] [#5254](http://forum.plantuml.net/5254) `<plain>...</plain>` to remove default text style (eg `skinparam classFontStyle`)
- [ ] [#5574](http://forum.plantuml.net/5574) tooltip over link

## Images, Icons, Sprites, Shapes, Embellishments
- [ ] [#4080](http://forum.plantuml.net/4080) Import images from jar/zip
- [ ] [#3790](http://forum.plantuml.net/3790) DATA URI as embeded image
- [ ] [#7485](http://forum.plantuml.net/7485) skinparam `DiagonalCorner`
- [ ] [#2899](http://forum.plantuml.net/2899) skinparam `activityShape`
- [ ] [#4076](http://forum.plantuml.net/4076), [#4079](http://forum.plantuml.net/4079) Sprites on stereotypes

## Color
- [ ] [#3770](http://forum.plantuml.net/3770) Inline set of multiple colors in various diagrams (`text;line;back;header`)
- [ ] [#1487](http://forum.plantuml.net/1487) `##[style]color` of node borders: works for class and state diagrams
- [ ] [#5340](http://forum.plantuml.net/5340) inline coloring of node borders
- [ ] [#7287](http://forum.plantuml.net/7287) automatic color
- [ ] [#3648](http://forum.plantuml.net/3648) Transparent color

## Arrows
- [ ] [#3636](http://forum.plantuml.net/3636) Arrows from/to class members
- [ ] [#3621](http://forum.plantuml.net/3621) Component diagram consumer/provider arrows
- [ ] make sure all arrow params are documented: `dotted|dashed|plain|bold|hidden|norank|single|thickness|left|right|up|down`, color
- [ ] [#3816](http://forum.plantuml.net/3816) skinparam ArrowColor, stereotyped arrows, new syntax for inline arrow style (Setting multiple arrow skinparams in one line); (componentArrowColor is deprecated)
- [ ] [#4949](http://forum.plantuml.net/4949) Inline setting for edge style and thickness
- [ ] [#4260](http://forum.plantuml.net/4260) `bold` and `plain` arrow styles
- [ ] [#4181](http://forum.plantuml.net/4181) `bold, dashed, dotted`

Make sure all arrow types are documented on one page:
- [ ] `arrows arrows-2` at https://github.com/anoff/blog/tree/master/static/assets/plantuml/diagrams
- [ ] [#1736](http://forum.plantuml.net/1736) Multiple lollipop edge styles
- [ ] [#5261](http://forum.plantuml.net/5261) crows foot edge
- [ ] [#2259](http://forum.plantuml.net/2259) Class diagram `--(` and `-0)-` arrows
- [ ] [#310](http://forum.plantuml.net/310) Sequence diagram `?->` and `->?` arrows

## Mixed and Embedded Diagrams
- [ ] [#2335](http://forum.plantuml.net/2335) `allow_mixing` vs `mix_usecase mix_actor...`
- [ ] [#375](http://forum.plantuml.net/375) Embed SVG in SVG diagram
- [ ] [#2427](http://forum.plantuml.net/2427) Embed SALT UI diagrams in notes and other texts ("Flowchat")

## Alternative Layoters
- [ ] [#4436](http://forum.plantuml.net/4436), [#5336](http://forum.plantuml.net/5336), [smetana02](http://plantuml.com/smetana02) `!pragma graphviz_dot jdot`: replace graphviz with Java code
- [x] [vizjs](http://plantuml.com/vizjs) `-graphvizdot vizjs`: replace graphviz with JavaScript code
- [ ] http://beta.plantuml.net/noditaa/: replace ditaa with java code

## Class Diagrams
- [ ] [#5835](http://forum.plantuml.net/5835) Notes on class fields
- [ ] [#3054](http://forum.plantuml.net/3054) details on how the "attributes" vs "methods" boxes are formed, and what happens when you add your own divider line
- [ ] [#2913](http://forum.plantuml.net/2913) Hide private / protected / package class members
- [ ] [#3448](http://forum.plantuml.net/3448) Tree structure inside class
- [ ] [#3424](http://forum.plantuml.net/3424) Class attribute stereotype
- [ ] [#2259](http://forum.plantuml.net/2259) Class diagram circle
- [ ] [#2239](http://forum.plantuml.net/2239) extends and implements can reference multiple nodes
- [ ] [#3193](http://forum.plantuml.net/3193) `skinparam groupInheritance` to merge inheritance arrows going to the same parent
- [ ] [#1638](http://forum.plantuml.net/1638) package style `card`

## Sequence Diagrams
[teoz](http://plantuml.com/teoz), [sequence-diagram#anchors_and_duration](http://wiki.plantuml.net/site/sequence-diagram#anchors_and_duration:), [tag/teoz](http://forum.plantuml.net/tag/teoz): new Teoz (vs old Puma) for sequence diagrams
- [ ] [#7119](http://forum.plantuml.net/7119) `%autonumber%`
- [ ] [#8511](http://forum.plantuml.net/8511) `autonumber inc`
- [ ] [#2794](http://forum.plantuml.net/2794) skinparam lifelineStrategy
- [ ] [#2503](http://forum.plantuml.net/2503) Secondary group label in sequence diagram
- [ ] [#7264](http://forum.plantuml.net/7264) skinparam belowForResponse
- [ ] [#1047](http://forum.plantuml.net/1047) skinparam style strictuml: emits triangle rather than sharp arrow heads
- [ ] [#3482](http://forum.plantuml.net/3482), [#206](http://forum.plantuml.net/206) skinparam sequenceMessageAlign

## Activity Diagrams
- [ ] [#5201](http://forum.plantuml.net/5201) skinparam swimlaneWidth
- [ ] [#2681](http://forum.plantuml.net/2681) Swimlane alias
- [ ] [#4470](http://forum.plantuml.net/4470) Label of arrows of repeat loops (`repeat while`)
- [ ] [#6105](http://forum.plantuml.net/6105) Activity diagram break
- [ ] [#301](http://forum.plantuml.net/301) Activity Beta `if (...) is/equals (...) then`
- [ ] [#265](http://forum.plantuml.net/265) Activity Beta kill
- [ ] [#3931](http://forum.plantuml.net/3931) `!pragma useVerticalIf on`: draw `if/elseif/else` structure vertically
- [ ] [#1626](http://forum.plantuml.net/1626) Activity diagram GOTO
- [ ] [#2792](http://forum.plantuml.net/2792) `skinparam activityArrowFontSize`
- [ ] [#3166](http://forum.plantuml.net/3166) `skinparam activityArrowFontColor`
- [ ] [#5346](http://forum.plantuml.net/5346) Activity diagram joinspec
- [ ] [#2868](http://forum.plantuml.net/2868) Activity diagram multiple halting states
- [ ] [#3505](http://forum.plantuml.net/3505) Activity diagram end
- [ ] [#5826](http://forum.plantuml.net/5826) backward on loops
- [ ] [#4906](http://forum.plantuml.net/4906) Gradient color on activity diagram partition
- [ ] [#2398](http://forum.plantuml.net/2398) Note on partition
- [ ] [#2793](http://forum.plantuml.net/2793) Inline coloring of partition
- [ ] [#1290](http://forum.plantuml.net/1290) `skinparam conditionStyle`: `inside` (hexagon: default), `foo1` (big diamond), `diamond` (tiny diamond)
- [ ] [#6010](http://forum.plantuml.net/6010) skinparam arrowMessageAlign center
- [ ] [#4411](http://forum.plantuml.net/4411) skinparam colorArrowSeparationSpace: multiple parallel arrows in activity digrams
- [ ] [#3770](http://forum.plantuml.net/3770) background color of `alt/group`

## State Diagrams
- [ ] [#1159](http://forum.plantuml.net/1159) State diagram `<<choice>>, <<fork>>, <<join>>, <<end>>`
- [ ] [#3672](http://forum.plantuml.net/3672) State Diagram `<<choice>>`
- [ ] [#10077](http://forum.plantuml.net/10077) colored connectors in state diagrams
- [ ] [#1159](http://forum.plantuml.net/1159) Choice Pseudostate in State Diagrams
- [ ] [#1099](http://forum.plantuml.net/1099) State diagram hide empty description
- [ ] [#4309](http://forum.plantuml.net/4309) State diagram `<<expansionInput>>` and `<<expansionOutput>>`, `<<inputPin>>` and `<<outputPin>>`, `<<entrypoint>>` and `<<exitpoint>>`
- [ ] [#1812](http://forum.plantuml.net/1812) State inline color

## SDL and ER/IE Diagrams
- [ ] [#1232](http://forum.plantuml.net/1232) SDL shapes (some undocumented)
- [x] [ie-diagram](http://plantuml.com/ie-diagram), [pull/31](https://github.com/plantuml/plantuml/pull/31) ER (IE) diagrams

## SALT (UI) Diagrams
[search?q=salt](https://forum.plantuml.net/search?q=salt), [tag/salt](https://forum.plantuml.net/tag/salt)
- [ ] [#5849](http://forum.plantuml.net/5849) Salt pseudo "sprite"
- [ ] [#5840](http://forum.plantuml.net/5840) Salt titled groupbox
- [ ] [#1265](http://forum.plantuml.net/1265), [#5400](http://forum.plantuml.net/5400) Salt tree table (table-tree)

## Timing Diagrams
- [ ] [#5776](http://forum.plantuml.net/5776) Timing diagram coloring

## Gantt Charts
[gantt-diagram](http://plantuml.com/gantt-diagram)
- [ ] [#5782](http://forum.plantuml.net/5782) Arrow on Gantt Diagram
- [ ] [#5510](http://forum.plantuml.net/5510) Gantt diagram dates

## BPMN Diagrams
- [ ] [#5647](http://forum.plantuml.net/5647) BPMN (@startbpm  and  @endbpm)

## MindMap Diagrams
[mindmap-diagram](http://plantuml.com/mindmap-diagram)

## WBS Diagrams
Work Breakdown Structures, Organizational Breakdown Structures (organigrams)

[wbs-diagram](http://plantuml.com/wbs-diagram)

## Graphviz Diagrams
- [ ] [#4210](http://forum.plantuml.net/4210) When using Dot, PlantUML supports strict graph and digraph
- [ ] [#1206](http://forum.plantuml.net/1206) Dot `graph`

**Comment by Potherca** [comment]
THIS.IS.AMAZING!

I'm fairly certain I won't have any time to contribute (sadly), but I just wanted to say this is **awesome** work!

**Comment by bflorat** [comment]
- wildcards in remove / hide / restore 
ex :  `remove *`

- `remove @unlinked`    (component diagram)
https://forum.plantuml.net/11052/remove-unlinked-components

**Comment by VladimirAlexiev** [comment]
Added sec *Your Help Needed* with link to this list, the forum and slack:  http://alphadoc.plantuml.com/doc/markdown/en/start#yll09vktqqw4kdu256uv. Can anyone make it more sexy and attention-drawing?

@bflorat thanks for these 2 bullets, I see they were added to the main list

**Comment by Potherca** [comment]
@VladimirAlexiev Regarding

> Can anyone make it more sexy and attention-drawing?

Maybe we should ask @arnaudroques (or other maintainers?) to [pin this issue](https://docs.github.com/en/github/managing-your-work-on-github/pinning-an-issue-to-your-repository) so it appears at the top of the "Issues" page?

**Comment by pakluba** [comment]
PlantUML supports switch-case in the new Activity Diagram, but seems like it's not mentioned anywhere. It has some rendering glitches, so that's might be the case.

**Comment by VladimirAlexiev** [comment]
@pakluba added `switch case ...` in **Activity**.
Also `together` in **Layout**

**Comment by demeesterroel** [comment]
@VladimirAlexiev 
I'd like to help document some features as requested in this ticket, and  on https://plantuml-documentation.readthedocs.io/en/latest/this_site/from_forum.html?highlight=strictuml

Can you point me to some information on how to best contribute. Thanks .

**Comment by The-Lum** [comment]
Hello @demeesterroel,

>I'd like to help document some features...

For that, you can read:
- http://alphadoc.plantuml.com/doc/markdown/en/start
- http://alphadoc.plantuml.com/doc/markdown/en/a_begin_for_this_wiki

And here is the page with the same topics as this current GH page:
- http://alphadoc.plantuml.com/doc/markdown/en/undocumented

_And then contribute...
Thanks a lot._
Regards.

**Comment by VladimirAlexiev** [comment]
Hi @demeesterroel ! 
1.Could you merge the above list to this one? If you can't edit the issue description , add it as a comment and I'll merge
2. I'd guess a decent percent of the items are already documented. If you stumble upon such, please mark them as done
3. alphadoc does not respond for me. Furthermore, doc pages (eg. https://plantuml.com/activity-diagram-legacy) don't show edit links. @arnaudroques , what's up?
   - If Arnoud does not respond soon, please open a separate issue

**Comment by jhoehle** [comment]
Sequence Diagrams
 - [ ] &-notation to draw multiple arrows on the same line / time (Teoz only feature)

Mixed and embedded
 - [ ] [#15011](https://forum.plantuml.net/15011/please-add-sub-diagram-support-for-activity-diagram) `{{` nested/sub diagrams `}}` e.g. within note (more general than just salt within activity diagram, above #2427)

Meanwhile documented (@VladimirAlexiev please check them above)
- [x] \# 310 (->?) \# 1047 (strictuml) # 4247 (hide unlinked)

**Comment by The-Lum** [comment]
Hello @jhoehle, and all,

Thanks for the remarks.

For:
> - [ ] &-notation to draw multiple arrows on the same line / time (Teoz only feature)

We can add a point from [Sequence page](https://plantuml.com/sequence-diagram) to [Teoz page](https://plantuml.com/teoz). :+1:

For:
> - [ ] [#15011](https://forum.plantuml.net/15011/please-add-sub-diagram-support-for-activity-diagram) `{{` nested/sub diagrams `}}` e.g. within note (more general than just salt within activity diagram, above #2427)

I started this page:
- [Sub-diagram on _Alpha-doc_](http://alphadoc.plantuml.com/doc/markdown/en/sub-diagram)

_To continue to improve the doc..._
Regards.

**Comment by xeruf** [comment]
I think the mentioned Salt items are documented now: 
https://plantuml.com/salt

**Comment by BenceSzalai** [comment]
Undocumented feature: using `$tag` to remove and hide elements. It is documented for [Component diagrams](https://plantuml.com/component-diagram#e966f55ffa507384). I've just added documentation for Class diagrams (based on #1240, waiting for approval, I think).

Other diagrams supporting `$tag` in need of documentation update based on my tests:
- use-case diagram
- state diagram
- deployment diagram
- archimate diagram

Diagram types not supporting `$tag`:
- sequence diagram
- activity-diagram, both legacy & new Beta
- object diagram
- timing diagram
- network diagram
- wireframe diagram
- gantt diagram
- mindmap diagram
- WBS diagram
- JSON diagram
- YAML diagram

Meanwhile [#11052](http://forum.plantuml.net/11052) can be ticked off the list, it is done:
- [Hide or Remove unlinked component](http://alphadoc.plantuml.com/doc/markdown/en/component-diagram#fdnjyxrq23qoklmlazyy)
- [Hide, Remove or Restore tagged component or wildcard](http://alphadoc.plantuml.com/doc/markdown/en/component-diagram#hzx3pc20vhm5kosjbzq3)
